server {
    location / {
        proxy_pass http://your-streamlit-app-url;
        proxy_set_header Host $host;
        proxy_set_header X-Frame-Options "";
        proxy_set_header Content-Security-Policy "frame-ancestors *";
    }
}